### ISSUE TITLE
test: `TimelineStepsFeature.AddAppointmentToTimeline`

### ISSUE THREAD

**Issue by tdashworth** [Capgemini/powerapps-specflow-bindings#165]
The test `Capgemini.PowerApps.SpecFlowBindings.UiTests.TimelineStepsFeature.AddAppointmentToTimeline` is failing.

```
Test method Capgemini.PowerApps.SpecFlowBindings.UiTests.TimelineStepsFeature.AddAppointmentToTimeline threw exception:
OpenQA.Selenium.NoSuchElementException: Field with name description does not exist.

   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute(IWebDriver driver)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.Timeline.AddAppointment(String subject, String location, String duration, String description)
   at Capgemini.PowerApps.SpecFlowBindings.Steps.TimelineSteps.WhenIAddAnAppointmentToTheTimeline(String subject, String description, String duration, String location) in \bindings\src\Capgemini.PowerApps.SpecFlowBindings\Steps\TimelineSteps.cs:line 27
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(IContextManager contextManager, StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
```

https://dev.azure.com/capgeminiuk/GitHub%20Support/_build/results?buildId=8397&view=ms.vss-test-web.build-test-results-tab&runId=1015498&resultId=100161&paneView=debug

**Comment by omkarkulkarni2704** [comment]
```
WebDriverWait wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
IWebElement descriptionField = wait.Until(ExpectedConditions.ElementIsVisible(By.Name("description")));

```

If the element is still not found, double-check the page's HTML to confirm that the ```description``` field exists and that its ```name``` attribute is correctly specified.
